spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/sandbox?useUnicode=true&characterEncoding=UTF8
  username: postgres
  password: postgres
  test-while-idle: true
  validation-query: SELECT 1
  validation-interval: 30000
